/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PeriodicTable;

import java.awt.event.KeyEvent;

/**
 *
 * @author MKS
 */
public class Boron extends javax.swing.JFrame {

    /**
     * Creates new form Boron
     */
    public Boron() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel869 = new javax.swing.JLabel();
        jLabel872 = new javax.swing.JLabel();
        jLabel873 = new javax.swing.JLabel();
        jLabel893 = new javax.swing.JLabel();
        jLabel895 = new javax.swing.JLabel();
        jLabel896 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel980 = new javax.swing.JLabel();
        jLabel981 = new javax.swing.JLabel();
        jLabel982 = new javax.swing.JLabel();
        jLabel983 = new javax.swing.JLabel();
        jLabel984 = new javax.swing.JLabel();
        jLabel985 = new javax.swing.JLabel();
        jLabel986 = new javax.swing.JLabel();
        jLabel987 = new javax.swing.JLabel();
        jLabel988 = new javax.swing.JLabel();
        jLabel989 = new javax.swing.JLabel();
        jLabel990 = new javax.swing.JLabel();
        jLabel991 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel894 = new javax.swing.JLabel();
        jLabel905 = new javax.swing.JLabel();
        jLabel906 = new javax.swing.JLabel();
        jLabel916 = new javax.swing.JLabel();
        jLabel928 = new javax.swing.JLabel();
        jLabel875 = new javax.swing.JLabel();
        jLabel870 = new javax.swing.JLabel();
        jLabel911 = new javax.swing.JLabel();
        jLabel943 = new javax.swing.JLabel();
        jLabel944 = new javax.swing.JLabel();
        jLabel941 = new javax.swing.JLabel();
        jLabel942 = new javax.swing.JLabel();
        jLabel939 = new javax.swing.JLabel();
        jLabel940 = new javax.swing.JLabel();
        jLabel947 = new javax.swing.JLabel();
        jLabel992 = new javax.swing.JLabel();
        jLabel993 = new javax.swing.JLabel();
        jLabel976 = new javax.swing.JLabel();
        jLabel1016 = new javax.swing.JLabel();
        jLabel1060 = new javax.swing.JLabel();
        jLabel1042 = new javax.swing.JLabel();
        jLabel1047 = new javax.swing.JLabel();
        jLabel978 = new javax.swing.JLabel();
        jLabel958 = new javax.swing.JLabel();
        jLabel994 = new javax.swing.JLabel();
        jLabel997 = new javax.swing.JLabel();
        jLabel999 = new javax.swing.JLabel();
        jLabel995 = new javax.swing.JLabel();
        jLabel962 = new javax.swing.JLabel();
        jLabel934 = new javax.swing.JLabel();
        jLabel935 = new javax.swing.JLabel();
        jLabel963 = new javax.swing.JLabel();
        jLabel961 = new javax.swing.JLabel();
        jLabel960 = new javax.swing.JLabel();
        jLabel932 = new javax.swing.JLabel();
        jLabel929 = new javax.swing.JLabel();
        jLabel931 = new javax.swing.JLabel();
        jLabel930 = new javax.swing.JLabel();
        jLabel938 = new javax.swing.JLabel();
        jLabel949 = new javax.swing.JLabel();
        jLabel912 = new javax.swing.JLabel();
        jLabel918 = new javax.swing.JLabel();
        jLabel917 = new javax.swing.JLabel();
        jLabel920 = new javax.swing.JLabel();
        jLabel915 = new javax.swing.JLabel();
        jLabel922 = new javax.swing.JLabel();
        jLabel923 = new javax.swing.JLabel();
        jLabel924 = new javax.swing.JLabel();
        jLabel925 = new javax.swing.JLabel();
        jLabel926 = new javax.swing.JLabel();
        jLabel927 = new javax.swing.JLabel();
        jLabel921 = new javax.swing.JLabel();
        jLabel919 = new javax.swing.JLabel();
        jLabel948 = new javax.swing.JLabel();
        jLabel913 = new javax.swing.JLabel();
        jLabel914 = new javax.swing.JLabel();
        jLabel909 = new javax.swing.JLabel();
        jLabel910 = new javax.swing.JLabel();
        jLabel908 = new javax.swing.JLabel();
        jLabel904 = new javax.swing.JLabel();
        jLabel903 = new javax.swing.JLabel();
        jLabel907 = new javax.swing.JLabel();
        jLabel901 = new javax.swing.JLabel();
        jLabel902 = new javax.swing.JLabel();
        jLabel899 = new javax.swing.JLabel();
        jLabel900 = new javax.swing.JLabel();
        jLabel946 = new javax.swing.JLabel();
        jLabel1061 = new javax.swing.JLabel();
        jLabel1043 = new javax.swing.JLabel();
        jLabel1048 = new javax.swing.JLabel();
        jLabel1049 = new javax.swing.JLabel();
        jLabel964 = new javax.swing.JLabel();
        jLabel965 = new javax.swing.JLabel();
        jLabel966 = new javax.swing.JLabel();
        jLabel945 = new javax.swing.JLabel();
        jLabel950 = new javax.swing.JLabel();
        jLabel951 = new javax.swing.JLabel();
        jLabel952 = new javax.swing.JLabel();
        jLabel996 = new javax.swing.JLabel();
        jLabel998 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boron");
        setPreferredSize(new java.awt.Dimension(585, 720));
        setResizable(false);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane8.setPreferredSize(new java.awt.Dimension(585, 720));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel869.setBackground(new java.awt.Color(255, 255, 255));
        jLabel869.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel869.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel869.setText("<html> <body> <center> <sub> 5</sub> B</center> </body> </html>");
        jLabel869.setOpaque(true);
        jPanel23.add(jLabel869, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 550, 40));

        jLabel872.setBackground(new java.awt.Color(255, 255, 255));
        jLabel872.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel872.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/727px-Boron_mNACTEC.jpg"))); // NOI18N
        jLabel872.setOpaque(true);
        jPanel23.add(jLabel872, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 550, 230));

        jLabel873.setBackground(new java.awt.Color(255, 255, 255));
        jLabel873.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel873.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel873.setText("Black-brown");
        jLabel873.setToolTipText("");
        jLabel873.setOpaque(true);
        jPanel23.add(jLabel873, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 550, 40));

        jLabel893.setBackground(new java.awt.Color(204, 204, 0));
        jLabel893.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel893.setForeground(new java.awt.Color(51, 51, 51));
        jLabel893.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel893.setText("<html> <body> <center> History</center> </body> </html>");
        jLabel893.setOpaque(true);
        jPanel23.add(jLabel893, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 800, 550, 40));

        jLabel895.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel895.setText("Solid");
        jLabel895.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel895, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 960, 320, 40));

        jLabel896.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel896.setText("Phase");
        jLabel896.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel896, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 960, 230, 40));

        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jButton8.setText("Return To Table");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton8KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 378, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel980.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel980.setText("Element category");
        jLabel980.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel980, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 230, 40));

        jLabel981.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel981.setText("Metalloid");
        jLabel981.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel981, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 320, 40));

        jLabel982.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel982.setText("Pronunciation");
        jLabel982.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel982, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 230, 40));

        jLabel983.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel983.setText("/ˈbɔrɒn/");
        jLabel983.setToolTipText("");
        jLabel983.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel983, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 320, 40));

        jLabel984.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel984.setText("Group, period, block");
        jLabel984.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel984, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 230, 40));

        jLabel985.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel985.setText("13, 2, p");
        jLabel985.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel985, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 320, 40));

        jLabel986.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel986.setText("Name, symbol, number");
        jLabel986.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel986, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 40));

        jLabel987.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel987.setText("Boron, B, 5");
        jLabel987.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel987, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 320, 40));

        jLabel988.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel988.setText("Standard atomic weight");
        jLabel988.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel988, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 230, 40));

        jLabel989.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel989.setText("10.811(7)");
        jLabel989.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel989, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 320, 40));

        jLabel990.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel990.setText("Electron configuration");
        jLabel990.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel990, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 230, 110));

        jLabel991.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel991.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel991.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/558px-Electron_shell_005_Boron.svg.png"))); // NOI18N
        jLabel991.setText("5:Boron   2,3");
        jLabel991.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel991.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel991.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel23.add(jLabel991, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 690, 320, 110));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("<html>\n<body>\n[He] 2s<sup>2</sup> 2p<sup>1</sup>\n<br>2, 3\n</body>\n</html>\n\n\n\n\n\n");
        jPanel23.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, 130, 50));

        jLabel4.setBackground(new java.awt.Color(204, 204, 0));
        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>\n<body>\n<center>\n\nBoron\n\n</center>\n</body>\n</html>");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        jPanel23.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 40));

        jLabel8.setBackground(new java.awt.Color(204, 204, 0));
        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Appearance");
        jLabel8.setOpaque(true);
        jPanel23.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 550, 40));

        jLabel21.setBackground(new java.awt.Color(204, 204, 0));
        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("<html> <body> <center> General Properties</center> </body> </html>");
        jLabel21.setOpaque(true);
        jPanel23.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 550, 40));

        jLabel894.setBackground(new java.awt.Color(204, 204, 0));
        jLabel894.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel894.setForeground(new java.awt.Color(51, 51, 51));
        jLabel894.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel894.setText("<html> <body> <center> Physical Properties </center> </body> </html>");
        jLabel894.setOpaque(true);
        jPanel23.add(jLabel894, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 920, 550, 40));

        jLabel905.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel905.setText("Discovery");
        jLabel905.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel905, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 840, 230, 40));

        jLabel906.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel906.setText("J. Gay-Lussac & L. Thénard (June 30 1808)");
        jLabel906.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel906, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 840, 320, 40));

        jLabel916.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel916.setText("First isolation");
        jLabel916.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel916, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 230, 40));

        jLabel928.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel928.setText("H. Davy (July 9 1808)");
        jLabel928.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel928, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 880, 320, 40));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel875.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel875.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel875.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/558px-Electron_shell_003_Lithium.svg.png"))); // NOI18N
        jLabel875.setText("3:Lithium                   2,1");
        jLabel875.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel875.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel22.add(jLabel875, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 790, 320, 150));

        jLabel870.setBackground(new java.awt.Color(204, 204, 0));
        jLabel870.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel870.setForeground(new java.awt.Color(51, 51, 51));
        jLabel870.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel870.setText("<html> <body> <center> Most stable isotopes </center> </body> </html>");
        jLabel870.setOpaque(true);
        jPanel22.add(jLabel870, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2160, 550, 40));

        jLabel911.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel911.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel911.setText("Main article: Isotopes of boron");
        jLabel911.setToolTipText("");
        jLabel911.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel911, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2200, 550, 40));

        jLabel943.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel943.setText("Thermal conductivity");
        jLabel943.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel943, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1960, 230, 40));

        jLabel944.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel944.setText("<html> <body> 27.4 W·m <sup>−1</sup>·K<sup>−1</sup> </body> </html>");
        jLabel944.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel944, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1960, 320, 40));

        jLabel941.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel941.setText("Magnetic ordering");
        jLabel941.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel941, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1880, 230, 40));

        jLabel942.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel942.setText("Diamagnetic");
        jLabel942.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel942, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1880, 320, 40));

        jLabel939.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel939.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel939.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/139px-Rhombohedral.svg.png"))); // NOI18N
        jLabel939.setText("Rhombohedral            ");
        jLabel939.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel939.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel22.add(jLabel939, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1760, 320, 120));

        jLabel940.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel940.setText("Crystal structure");
        jLabel940.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel940, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1760, 230, 120));

        jLabel947.setBackground(new java.awt.Color(204, 204, 0));
        jLabel947.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel947.setForeground(new java.awt.Color(51, 51, 51));
        jLabel947.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel947.setText("<html> <body> <center> Miscellanea</center> </body> </html>");
        jLabel947.setOpaque(true);
        jPanel22.add(jLabel947, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1720, 550, 40));

        jLabel992.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel992.setText("CAS registry number");
        jLabel992.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel992, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2120, 230, 40));

        jLabel993.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel993.setText("7440-42-8");
        jLabel993.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel993, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2120, 320, 40));

        jLabel976.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel976.setText("Speed of sound (thin rod)");
        jLabel976.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel976, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2040, 230, 40));

        jLabel1016.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1016.setText("<html>\n<body>\n(20 °C) 16,200   m·s\n<sup>−1</sup>\n</body>\n</html> \t");
        jLabel1016.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1016, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2040, 320, 40));

        jLabel1060.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1060.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1060.setText("<html> <body> <sup>10</sup>B</body> </html>");
        jLabel1060.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1060, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2280, 70, 40));

        jLabel1042.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1042.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1042.setText("19.9(7)%*");
        jLabel1042.setToolTipText("");
        jLabel1042.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1042, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2280, 110, 40));

        jLabel1047.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1047.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1047.setText("<html>\n<body>\n<sup>10</sup>B is stable with 5 neutrons\n</body>\n</html>");
        jLabel1047.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1047, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2280, 370, 40));

        jLabel978.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel978.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel978.setText("iso");
        jLabel978.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel978, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2240, 70, 40));

        jLabel958.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel958.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel958.setText("NA");
        jLabel958.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel958, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2240, 110, 40));

        jLabel994.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel994.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel994.setText("half-life");
        jLabel994.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel994, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2240, 90, 40));

        jLabel997.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel997.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel997.setText("DM \t");
        jLabel997.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel997, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 2240, 80, 40));

        jLabel999.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel999.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel999.setText("DE (MeV)");
        jLabel999.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel999, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2240, 120, 40));

        jLabel995.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel995.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel995.setText("DP");
        jLabel995.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel995, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 2240, 80, 40));

        jLabel962.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel962.setText("Covalent radius");
        jLabel962.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel962, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1640, 230, 40));

        jLabel934.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel934.setText("Van der Waals radius");
        jLabel934.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel934, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1680, 230, 40));

        jLabel935.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel935.setText("192 pm");
        jLabel935.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel935, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1680, 320, 40));

        jLabel963.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel963.setText("84±3 pm");
        jLabel963.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel963, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1640, 320, 40));

        jLabel961.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel961.setText("<html> <body> 3rd:  3659.7   kJ·mol <sup>−1</sup> </body> </html>");
        jLabel961.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel961, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1560, 320, 40));

        jLabel960.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel960.setText("<html> <body> 1st:  800.6  kJ·mol <sup>−1</sup> </body> </html> ");
        jLabel960.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel960, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1480, 320, 40));

        jLabel932.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel932.setText("Ionization energies(more)");
        jLabel932.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel932, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1480, 230, 120));

        jLabel929.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel929.setText("Oxidation states");
        jLabel929.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel929, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1400, 230, 40));

        jLabel931.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel931.setText("3, 2, 1 \n(mildly acidic oxide)");
        jLabel931.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel931, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1400, 320, 40));

        jLabel930.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel930.setText("Electronegativity");
        jLabel930.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel930, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1440, 230, 40));

        jLabel938.setBackground(new java.awt.Color(204, 204, 0));
        jLabel938.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel938.setForeground(new java.awt.Color(51, 51, 51));
        jLabel938.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel938.setText("<html> <body> <center> Atomic properties</center> </body> </html>");
        jLabel938.setOpaque(true);
        jPanel22.add(jLabel938, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1360, 550, 40));

        jLabel949.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel949.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel949.setText("P (Pa)");
        jLabel949.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel949, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1280, 120, 40));

        jLabel912.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel912.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel912.setText("at T (K)");
        jLabel912.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel912, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1320, 120, 40));

        jLabel918.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel918.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel918.setText("1");
        jLabel918.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel918, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1280, 60, 40));

        jLabel917.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel917.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel917.setText("2562");
        jLabel917.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel917, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1320, 60, 40));

        jLabel920.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel920.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel920.setText("10");
        jLabel920.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel920, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1280, 60, 40));

        jLabel915.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel915.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel915.setText("2348");
        jLabel915.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel915, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1320, 60, 40));

        jLabel922.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel922.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel922.setText("100");
        jLabel922.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel922, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1280, 60, 40));

        jLabel923.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel923.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel923.setText("2822");
        jLabel923.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel923, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1320, 60, 40));

        jLabel924.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel924.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel924.setText("1 k");
        jLabel924.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel924, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1280, 70, 40));

        jLabel925.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel925.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel925.setText("3141");
        jLabel925.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel925, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1320, 70, 40));

        jLabel926.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel926.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel926.setText("10 k");
        jLabel926.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel926, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1280, 80, 40));

        jLabel927.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel927.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel927.setText("3545");
        jLabel927.setToolTipText("");
        jLabel927.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel927, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1320, 80, 40));

        jLabel921.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel921.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel921.setText("100 k");
        jLabel921.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel921, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1280, 100, 40));

        jLabel919.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel919.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel919.setText("4072");
        jLabel919.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel919, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1320, 100, 40));

        jLabel948.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel948.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel948.setText("Vapor pressure ");
        jLabel948.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel948, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1240, 550, 40));

        jLabel913.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel913.setText("<html>\n<body>\n11.087 J·mol\n<sup>−1</sup>\n·K<sup>−1</sup>\n</body>\n</html>\n");
        jLabel913.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel913, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1200, 320, 40));

        jLabel914.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel914.setText("Molar heat capacity");
        jLabel914.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel914, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1200, 230, 40));

        jLabel909.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel909.setText("Heat of vaporization");
        jLabel909.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel909, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1160, 230, 40));

        jLabel910.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel910.setText("<html> <body>480 kJ·mol <sup>−1</sup> </body> </html>");
        jLabel910.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel910, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1160, 320, 40));

        jLabel908.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel908.setText("<html> <body>  50.2  kJ·mol <sup>−1</sup> </body> </html>");
        jLabel908.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel908, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1120, 320, 40));

        jLabel904.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel904.setText("4200 K, 3927 °C, 7101 °F");
        jLabel904.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel904, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1080, 320, 40));

        jLabel903.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel903.setText("Boiling point");
        jLabel903.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel903, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1080, 230, 40));

        jLabel907.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel907.setText("Heat of fusion");
        jLabel907.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel907, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1120, 230, 40));

        jLabel901.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel901.setText("Melting point");
        jLabel901.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel901, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1040, 230, 40));

        jLabel902.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel902.setText(" \t2349 K, 2076 °C, 3769 °F");
        jLabel902.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel902, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1040, 320, 40));

        jLabel899.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel899.setText("Liquid density at m.p.");
        jLabel899.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel899, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1000, 230, 40));

        jLabel900.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel900.setText("<html> <body>2.08 g·cm <sup>−3</sup> </body> </html>");
        jLabel900.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel900, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1000, 320, 40));

        jLabel946.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel946.setText("2.04 (Pauling scale)");
        jLabel946.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel946, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1440, 320, 40));

        jLabel1061.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1061.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1061.setText("<html> <body> <sup>11</sup>B</body> </html>");
        jLabel1061.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1061, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2320, 70, 40));

        jLabel1043.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1043.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1043.setText("80.1(7)%*");
        jLabel1043.setToolTipText("");
        jLabel1043.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1043, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2320, 110, 40));

        jLabel1048.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1048.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1048.setText("<html>\n<body>\n<sup>11</sup>B is stable with 6 neutrons\n</body>\n</html> \t");
        jLabel1048.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1048, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2320, 370, 40));

        jLabel1049.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1049.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1049.setText("<html>\n<body>\n<center>\n*Boron-10 content may be as low as 19.1% and as<br>\nhigh as 20.3% in natural samples. Boron-11 is<br>\nthe remainder in such cases.\n</center>\n</body>\n</htmL>");
        jLabel1049.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1049, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2360, 550, 80));

        jLabel964.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel964.setText("<html> <body> 2nd: 2427.1 kJ·mol <sup>−1</sup> </body> </html>");
        jLabel964.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel964, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1520, 320, 40));

        jLabel965.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel965.setText("Atomic radius");
        jLabel965.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel965, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1600, 230, 40));

        jLabel966.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel966.setText("90 pm");
        jLabel966.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel966, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1600, 320, 40));

        jLabel945.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel945.setText("Electrical resistivity");
        jLabel945.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel945, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1920, 230, 40));

        jLabel950.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel950.setText("<html>\n<body>\n(20 °C) ~10<sup>6</sup> Ω·m\n</body>\n</html>");
        jLabel950.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel950, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1920, 320, 40));

        jLabel951.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel951.setText("Thermal expansion");
        jLabel951.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel951, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2000, 230, 40));

        jLabel952.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel952.setText("<html> <body>(25 °C) (ß form) 5–7 µm.m <sup>−1</sup>·K<sup>−1</sup> </body> </html>");
        jLabel952.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel952, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2000, 320, 40));

        jLabel996.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel996.setText("Mohs hardness");
        jLabel996.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel996, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2080, 230, 40));

        jLabel998.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel998.setText(" \t~9.5");
        jLabel998.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel998, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2080, 320, 40));

        jScrollPane8.setViewportView(jPanel22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Periodic_TableNew Tab = new Periodic_TableNew();
        Tab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton8KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            Periodic_TableNew Tab = new Periodic_TableNew();
            Tab.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton8KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Boron().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1016;
    private javax.swing.JLabel jLabel1042;
    private javax.swing.JLabel jLabel1043;
    private javax.swing.JLabel jLabel1047;
    private javax.swing.JLabel jLabel1048;
    private javax.swing.JLabel jLabel1049;
    private javax.swing.JLabel jLabel1060;
    private javax.swing.JLabel jLabel1061;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel869;
    private javax.swing.JLabel jLabel870;
    private javax.swing.JLabel jLabel872;
    private javax.swing.JLabel jLabel873;
    private javax.swing.JLabel jLabel875;
    private javax.swing.JLabel jLabel893;
    private javax.swing.JLabel jLabel894;
    private javax.swing.JLabel jLabel895;
    private javax.swing.JLabel jLabel896;
    private javax.swing.JLabel jLabel899;
    private javax.swing.JLabel jLabel900;
    private javax.swing.JLabel jLabel901;
    private javax.swing.JLabel jLabel902;
    private javax.swing.JLabel jLabel903;
    private javax.swing.JLabel jLabel904;
    private javax.swing.JLabel jLabel905;
    private javax.swing.JLabel jLabel906;
    private javax.swing.JLabel jLabel907;
    private javax.swing.JLabel jLabel908;
    private javax.swing.JLabel jLabel909;
    private javax.swing.JLabel jLabel910;
    private javax.swing.JLabel jLabel911;
    private javax.swing.JLabel jLabel912;
    private javax.swing.JLabel jLabel913;
    private javax.swing.JLabel jLabel914;
    private javax.swing.JLabel jLabel915;
    private javax.swing.JLabel jLabel916;
    private javax.swing.JLabel jLabel917;
    private javax.swing.JLabel jLabel918;
    private javax.swing.JLabel jLabel919;
    private javax.swing.JLabel jLabel920;
    private javax.swing.JLabel jLabel921;
    private javax.swing.JLabel jLabel922;
    private javax.swing.JLabel jLabel923;
    private javax.swing.JLabel jLabel924;
    private javax.swing.JLabel jLabel925;
    private javax.swing.JLabel jLabel926;
    private javax.swing.JLabel jLabel927;
    private javax.swing.JLabel jLabel928;
    private javax.swing.JLabel jLabel929;
    private javax.swing.JLabel jLabel930;
    private javax.swing.JLabel jLabel931;
    private javax.swing.JLabel jLabel932;
    private javax.swing.JLabel jLabel934;
    private javax.swing.JLabel jLabel935;
    private javax.swing.JLabel jLabel938;
    private javax.swing.JLabel jLabel939;
    private javax.swing.JLabel jLabel940;
    private javax.swing.JLabel jLabel941;
    private javax.swing.JLabel jLabel942;
    private javax.swing.JLabel jLabel943;
    private javax.swing.JLabel jLabel944;
    private javax.swing.JLabel jLabel945;
    private javax.swing.JLabel jLabel946;
    private javax.swing.JLabel jLabel947;
    private javax.swing.JLabel jLabel948;
    private javax.swing.JLabel jLabel949;
    private javax.swing.JLabel jLabel950;
    private javax.swing.JLabel jLabel951;
    private javax.swing.JLabel jLabel952;
    private javax.swing.JLabel jLabel958;
    private javax.swing.JLabel jLabel960;
    private javax.swing.JLabel jLabel961;
    private javax.swing.JLabel jLabel962;
    private javax.swing.JLabel jLabel963;
    private javax.swing.JLabel jLabel964;
    private javax.swing.JLabel jLabel965;
    private javax.swing.JLabel jLabel966;
    private javax.swing.JLabel jLabel976;
    private javax.swing.JLabel jLabel978;
    private javax.swing.JLabel jLabel980;
    private javax.swing.JLabel jLabel981;
    private javax.swing.JLabel jLabel982;
    private javax.swing.JLabel jLabel983;
    private javax.swing.JLabel jLabel984;
    private javax.swing.JLabel jLabel985;
    private javax.swing.JLabel jLabel986;
    private javax.swing.JLabel jLabel987;
    private javax.swing.JLabel jLabel988;
    private javax.swing.JLabel jLabel989;
    private javax.swing.JLabel jLabel990;
    private javax.swing.JLabel jLabel991;
    private javax.swing.JLabel jLabel992;
    private javax.swing.JLabel jLabel993;
    private javax.swing.JLabel jLabel994;
    private javax.swing.JLabel jLabel995;
    private javax.swing.JLabel jLabel996;
    private javax.swing.JLabel jLabel997;
    private javax.swing.JLabel jLabel998;
    private javax.swing.JLabel jLabel999;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
