/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PeriodicTable;

import java.awt.event.KeyEvent;

/**
 *
 * @author MKS
 */
public class Francium extends javax.swing.JFrame {

    /**
     * Creates new form Francium
     */
    public Francium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel869 = new javax.swing.JLabel();
        jLabel871 = new javax.swing.JLabel();
        jLabel873 = new javax.swing.JLabel();
        jLabel874 = new javax.swing.JLabel();
        jLabel893 = new javax.swing.JLabel();
        jLabel895 = new javax.swing.JLabel();
        jLabel896 = new javax.swing.JLabel();
        jLabel897 = new javax.swing.JLabel();
        jLabel898 = new javax.swing.JLabel();
        jLabel901 = new javax.swing.JLabel();
        jLabel902 = new javax.swing.JLabel();
        jLabel903 = new javax.swing.JLabel();
        jLabel904 = new javax.swing.JLabel();
        jLabel907 = new javax.swing.JLabel();
        jLabel908 = new javax.swing.JLabel();
        jLabel909 = new javax.swing.JLabel();
        jLabel910 = new javax.swing.JLabel();
        jLabel912 = new javax.swing.JLabel();
        jLabel915 = new javax.swing.JLabel();
        jLabel917 = new javax.swing.JLabel();
        jLabel918 = new javax.swing.JLabel();
        jLabel919 = new javax.swing.JLabel();
        jLabel920 = new javax.swing.JLabel();
        jLabel921 = new javax.swing.JLabel();
        jLabel922 = new javax.swing.JLabel();
        jLabel923 = new javax.swing.JLabel();
        jLabel924 = new javax.swing.JLabel();
        jLabel925 = new javax.swing.JLabel();
        jLabel926 = new javax.swing.JLabel();
        jLabel927 = new javax.swing.JLabel();
        jLabel928 = new javax.swing.JLabel();
        jLabel929 = new javax.swing.JLabel();
        jLabel930 = new javax.swing.JLabel();
        jLabel931 = new javax.swing.JLabel();
        jLabel932 = new javax.swing.JLabel();
        jLabel936 = new javax.swing.JLabel();
        jLabel937 = new javax.swing.JLabel();
        jLabel938 = new javax.swing.JLabel();
        jLabel948 = new javax.swing.JLabel();
        jLabel949 = new javax.swing.JLabel();
        jLabel960 = new javax.swing.JLabel();
        jLabel962 = new javax.swing.JLabel();
        jLabel963 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel876 = new javax.swing.JLabel();
        jLabel980 = new javax.swing.JLabel();
        jLabel981 = new javax.swing.JLabel();
        jLabel982 = new javax.swing.JLabel();
        jLabel983 = new javax.swing.JLabel();
        jLabel984 = new javax.swing.JLabel();
        jLabel985 = new javax.swing.JLabel();
        jLabel986 = new javax.swing.JLabel();
        jLabel987 = new javax.swing.JLabel();
        jLabel988 = new javax.swing.JLabel();
        jLabel989 = new javax.swing.JLabel();
        jLabel990 = new javax.swing.JLabel();
        jLabel991 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel875 = new javax.swing.JLabel();
        jLabel954 = new javax.swing.JLabel();
        jLabel958 = new javax.swing.JLabel();
        jLabel957 = new javax.swing.JLabel();
        jLabel952 = new javax.swing.JLabel();
        jLabel870 = new javax.swing.JLabel();
        jLabel911 = new javax.swing.JLabel();
        jLabel964 = new javax.swing.JLabel();
        jLabel965 = new javax.swing.JLabel();
        jLabel941 = new javax.swing.JLabel();
        jLabel942 = new javax.swing.JLabel();
        jLabel939 = new javax.swing.JLabel();
        jLabel940 = new javax.swing.JLabel();
        jLabel947 = new javax.swing.JLabel();
        jLabel992 = new javax.swing.JLabel();
        jLabel993 = new javax.swing.JLabel();
        jLabel955 = new javax.swing.JLabel();
        jLabel1007 = new javax.swing.JLabel();
        jLabel1008 = new javax.swing.JLabel();
        jLabel1019 = new javax.swing.JLabel();
        jLabel1020 = new javax.swing.JLabel();
        jLabel1026 = new javax.swing.JLabel();
        jLabel979 = new javax.swing.JLabel();
        jLabel1035 = new javax.swing.JLabel();
        jLabel1014 = new javax.swing.JLabel();
        jLabel996 = new javax.swing.JLabel();
        jLabel1015 = new javax.swing.JLabel();
        jLabel998 = new javax.swing.JLabel();
        jLabel967 = new javax.swing.JLabel();
        jLabel1038 = new javax.swing.JLabel();
        jLabel1039 = new javax.swing.JLabel();
        jLabel1040 = new javax.swing.JLabel();
        jLabel959 = new javax.swing.JLabel();
        jLabel1010 = new javax.swing.JLabel();
        jLabel1011 = new javax.swing.JLabel();
        jLabel1016 = new javax.swing.JLabel();
        jLabel1012 = new javax.swing.JLabel();
        jLabel1042 = new javax.swing.JLabel();
        jLabel1043 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Francium");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(585, 720));
        setResizable(false);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane8.setPreferredSize(new java.awt.Dimension(585, 720));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel869.setBackground(new java.awt.Color(255, 255, 255));
        jLabel869.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel869.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel869.setText("<html> <body> <center> <sub>  87</sub> Fr</center> </body> </html>");
        jLabel869.setOpaque(true);
        jPanel23.add(jLabel869, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 550, 40));

        jLabel871.setBackground(new java.awt.Color(255, 153, 51));
        jLabel871.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel871.setForeground(new java.awt.Color(51, 51, 51));
        jLabel871.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel871.setText("<html> <body> <center>  Francium </center> </body> </html>");
        jLabel871.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel871.setOpaque(true);
        jPanel23.add(jLabel871, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 40));

        jLabel873.setBackground(new java.awt.Color(255, 255, 255));
        jLabel873.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel873.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel873.setText("Unknown, but probably metallic");
        jLabel873.setOpaque(true);
        jPanel23.add(jLabel873, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 550, 30));

        jLabel874.setBackground(new java.awt.Color(255, 153, 51));
        jLabel874.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel874.setForeground(new java.awt.Color(51, 51, 51));
        jLabel874.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel874.setText("<html> <body> <center> General properties  </center> </body> </html>");
        jLabel874.setOpaque(true);
        jPanel23.add(jLabel874, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 550, 40));

        jLabel893.setBackground(new java.awt.Color(255, 153, 51));
        jLabel893.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel893.setForeground(new java.awt.Color(51, 51, 51));
        jLabel893.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel893.setText("<html> <body> <center> Physical Properties </center> </body> </html>");
        jLabel893.setOpaque(true);
        jPanel23.add(jLabel893, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 550, 40));

        jLabel895.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel895.setText("Solid presumably");
        jLabel895.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel895, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 690, 320, 40));

        jLabel896.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel896.setText("Phase");
        jLabel896.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel896, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 230, 40));

        jLabel897.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel897.setText("Density (near r.t.)");
        jLabel897.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel897, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 230, 40));

        jLabel898.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel898.setText("<html> <body> ? 1.87 (extrapolated, not measured) g·cm <sup>−3</sup> </body> <html>");
        jLabel898.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel898, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 730, 320, 40));

        jLabel901.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel901.setText("Melting point");
        jLabel901.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel901, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 230, 40));

        jLabel902.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel902.setText("? 300 K, ? 27 °C, ? 80 °F");
        jLabel902.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel902, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 770, 320, 40));

        jLabel903.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel903.setText("Boiling point");
        jLabel903.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel903, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 230, 40));

        jLabel904.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel904.setText(" \t ? 950 K, ? 677 °C, ? 1250 °F");
        jLabel904.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel904, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 810, 320, 40));

        jLabel907.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel907.setText("Heat of fusion");
        jLabel907.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel907, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 850, 230, 40));

        jLabel908.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel908.setText("<html> <body> ca. 2 kJ·mol <sup>−1</sup> </body> </html>");
        jLabel908.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel908, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 850, 320, 40));

        jLabel909.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel909.setText("Heat of vaporization");
        jLabel909.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel909, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 890, 230, 40));

        jLabel910.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel910.setText("<html> <body>  \tca. 65 kJ·mol <sup>−1</sup> </body> </html>");
        jLabel910.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel910, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 890, 320, 40));

        jLabel912.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel912.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel912.setText("at T (K)");
        jLabel912.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel912, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1010, 120, 40));

        jLabel915.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel915.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel915.setText(" \t404");
        jLabel915.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel915, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1010, 60, 40));

        jLabel917.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel917.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel917.setText("454");
        jLabel917.setToolTipText("");
        jLabel917.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel917, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1010, 60, 40));

        jLabel918.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel918.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel918.setText("1");
        jLabel918.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel918, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 970, 60, 40));

        jLabel919.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel919.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel919.setText("946");
        jLabel919.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel919, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1010, 100, 40));

        jLabel920.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel920.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel920.setText("10");
        jLabel920.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel920, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 970, 60, 40));

        jLabel921.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel921.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel921.setText("100 k");
        jLabel921.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel921, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 970, 100, 40));

        jLabel922.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel922.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel922.setText("100");
        jLabel922.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel922, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 970, 60, 40));

        jLabel923.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel923.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel923.setText(" \t519 \t");
        jLabel923.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel923, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1010, 60, 40));

        jLabel924.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel924.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel924.setText("1 k");
        jLabel924.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel924, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 970, 70, 40));

        jLabel925.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel925.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel925.setText("608");
        jLabel925.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel925, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1010, 70, 40));

        jLabel926.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel926.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel926.setText("10 k");
        jLabel926.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel926, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 970, 80, 40));

        jLabel927.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel927.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel927.setText("738");
        jLabel927.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel927, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1010, 80, 40));

        jLabel928.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel928.setText("1 (strongly basic oxide)");
        jLabel928.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel928, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1090, 320, 40));

        jLabel929.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel929.setText("Oxidation states");
        jLabel929.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel929, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1090, 230, 40));

        jLabel930.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel930.setText("Electronegativity");
        jLabel930.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel930, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1130, 230, 40));

        jLabel931.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel931.setText(" \t0.7 (Pauling scale)");
        jLabel931.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel931, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1130, 320, 40));

        jLabel932.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel932.setText("Ionization energies ");
        jLabel932.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel932, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1170, 230, 40));

        jLabel936.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel936.setText("Van der Waals radius");
        jLabel936.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel936, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1250, 230, 40));

        jLabel937.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel937.setText("348 (extrapolated) pm");
        jLabel937.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel937, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1250, 320, 40));

        jLabel938.setBackground(new java.awt.Color(255, 153, 51));
        jLabel938.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel938.setForeground(new java.awt.Color(51, 51, 51));
        jLabel938.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel938.setText("<html> <body> <center> Atomic properties </center> </body> </html>");
        jLabel938.setOpaque(true);
        jPanel23.add(jLabel938, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1050, 550, 40));

        jLabel948.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel948.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel948.setText("Vapor pressure (extrapolated)");
        jLabel948.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel948, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 930, 550, 40));

        jLabel949.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel949.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel949.setText("P (Pa)");
        jLabel949.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel949, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 970, 120, 40));

        jLabel960.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel960.setText("<html> <body> 1st: 380  kJ·mol <sup>−1</sup> </body> </html> ");
        jLabel960.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel960, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1170, 320, 40));

        jLabel962.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel962.setText("Covalent radius");
        jLabel962.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel962, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1210, 230, 40));

        jLabel963.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel963.setText("260 (extrapolated) pm");
        jLabel963.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel963, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1210, 320, 40));

        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jButton8.setText("Return To Table");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton8KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 378, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel876.setBackground(new java.awt.Color(255, 153, 51));
        jLabel876.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel876.setForeground(new java.awt.Color(51, 51, 51));
        jLabel876.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel876.setText("<html>\n<body>\n<center>\n\nAppearance\n\n</center>\n</body>\n</html>");
        jLabel876.setOpaque(true);
        jPanel23.add(jLabel876, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 550, 40));

        jLabel980.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel980.setText("Element category");
        jLabel980.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel980, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 40));

        jLabel981.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel981.setText("Alkali metal");
        jLabel981.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel981, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 320, 40));

        jLabel982.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel982.setText("Pronunciation");
        jLabel982.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel982, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 40));

        jLabel983.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel983.setText(" \t/ˈfrænsiəm/ FRAN-see-əm");
        jLabel983.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel983, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 320, 40));

        jLabel984.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel984.setText("Group, period, block");
        jLabel984.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel984, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 40));

        jLabel985.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel985.setText("1, 7, s");
        jLabel985.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel985, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 320, 40));

        jLabel986.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel986.setText("Name, symbol, number");
        jLabel986.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel986, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 40));

        jLabel987.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel987.setText("Francium, Fr, 87");
        jLabel987.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel987, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 320, 40));

        jLabel988.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel988.setText("Standard atomic weight");
        jLabel988.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel988, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 230, 40));

        jLabel989.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel989.setText("(223)");
        jLabel989.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel989, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 320, 40));

        jLabel990.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel990.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel990.setText("Electron configuration");
        jLabel990.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel990, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 230, 200));

        jLabel991.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel991.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/558px-Electron_shell_087_Francium.svg.png"))); // NOI18N
        jLabel991.setText("87:Francium   2, 8, 18, 32, 18, 8, 1 ");
        jLabel991.setToolTipText("");
        jLabel991.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel991.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel991.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel23.add(jLabel991, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 320, 200));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("<html>\n<body>\n[Rn] 7s<sup>1</sup>\n<br>\n2, 8, 18, 32, 18, 8, 1 \n</body>\n</html>\n");
        jPanel23.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 130, 50));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel875.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel875.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel875.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/558px-Electron_shell_003_Lithium.svg.png"))); // NOI18N
        jLabel875.setText("3:Lithium                   2,1");
        jLabel875.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel875.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel22.add(jLabel875, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 790, 320, 150));

        jLabel954.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel954.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel954.setText("iso");
        jLabel954.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel954, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1650, 70, 40));

        jLabel958.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel958.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel958.setText("half-life");
        jLabel958.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel958, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1650, 90, 40));

        jLabel957.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel957.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel957.setText("NA");
        jLabel957.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel957, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1650, 110, 40));

        jLabel952.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel952.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel952.setText(" \t14.2 min");
        jLabel952.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel952, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1730, 90, 40));

        jLabel870.setBackground(new java.awt.Color(255, 153, 51));
        jLabel870.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel870.setForeground(new java.awt.Color(51, 51, 51));
        jLabel870.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel870.setText("<html> <body> <center> Most stable isotopes </center> </body> </html>");
        jLabel870.setOpaque(true);
        jPanel22.add(jLabel870, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1570, 550, 40));

        jLabel911.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel911.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel911.setText("Main article: Isotopes of francium");
        jLabel911.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel911, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1610, 550, 40));

        jLabel964.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel964.setText("3 µ (calculated)Ω·m");
        jLabel964.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel964, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1490, 320, 40));

        jLabel965.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel965.setText("Electrical resistivity");
        jLabel965.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel965, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1490, 230, 40));

        jLabel941.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel941.setText("Magnetic ordering");
        jLabel941.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel941, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1450, 230, 40));

        jLabel942.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel942.setText("Paramagnetic");
        jLabel942.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel942, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1450, 320, 40));

        jLabel939.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel939.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel939.setIcon(new javax.swing.ImageIcon("D:\\MKS\\IMAGE\\Edit\\Lithiumstr.png")); // NOI18N
        jLabel939.setText("<html>\n<body>\nCubic body-centered <br>\n(extrapolated)\n</body>\n</html>");
        jLabel939.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel939.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel22.add(jLabel939, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1330, 320, 120));

        jLabel940.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel940.setText("Crystal structure");
        jLabel940.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel940, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1330, 230, 120));

        jLabel947.setBackground(new java.awt.Color(255, 153, 51));
        jLabel947.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel947.setForeground(new java.awt.Color(51, 51, 51));
        jLabel947.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel947.setText("<html> <body> <center> Miscellanea</center> </body> </html>");
        jLabel947.setOpaque(true);
        jPanel22.add(jLabel947, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1290, 550, 40));

        jLabel992.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel992.setText("CAS registry number");
        jLabel992.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel992, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1530, 230, 40));

        jLabel993.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel993.setText("7440-73-5");
        jLabel993.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel993, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1530, 320, 40));

        jLabel955.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel955.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel955.setText("DP");
        jLabel955.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel955, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1650, 80, 40));

        jLabel1007.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1007.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1007.setText("DM \t");
        jLabel1007.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1007, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1650, 80, 40));

        jLabel1008.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1008.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1008.setText("DE (MeV)");
        jLabel1008.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1008, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1650, 120, 40));

        jLabel1019.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1019.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1019.setText("<html> <body> <sup>222</sup> Ra </body> </html>");
        jLabel1019.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1019, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1730, 80, 40));

        jLabel1020.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1020.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1020.setText("2.033");
        jLabel1020.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1020, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1730, 120, 40));

        jLabel1026.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1026.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1026.setText("<html> <body> β<sup>-</sup> </body> </html>");
        jLabel1026.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1026, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1730, 80, 40));

        jLabel979.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel979.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel979.setText("syn");
        jLabel979.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel979, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1730, 110, 40));

        jLabel1035.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1035.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1035.setText("<html> <body> <sup>217</sup> At </body> </html>");
        jLabel1035.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1035, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1690, 80, 40));

        jLabel1014.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1014.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1014.setText("<html> <body> <sup>222</sup> Fr </body> </html>");
        jLabel1014.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1014, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1730, 70, 40));

        jLabel996.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel996.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel996.setText("trace");
        jLabel996.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel996, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1690, 110, 40));

        jLabel1015.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1015.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1015.setText("<html> <body> <sup>223 </sup> Fr </body> </html>");
        jLabel1015.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1015, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1770, 70, 80));

        jLabel998.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel998.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel998.setText("trace");
        jLabel998.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel998, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1770, 110, 80));

        jLabel967.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel967.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel967.setText("22.00 min");
        jLabel967.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel967, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1770, 90, 80));

        jLabel1038.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1038.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1038.setText("<html> <body> β<sup>-</sup> </body> </html>");
        jLabel1038.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1038, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1770, 80, 40));

        jLabel1039.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1039.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1039.setText("5.430");
        jLabel1039.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1039, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1810, 120, 40));

        jLabel1040.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1040.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1040.setText("<html> <body> <sup>219</sup> At </body> </html>");
        jLabel1040.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1040, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1810, 80, 40));

        jLabel959.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel959.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel959.setText("4.8 min");
        jLabel959.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel959, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1690, 90, 40));

        jLabel1010.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1010.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1010.setText("α");
        jLabel1010.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1010, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1810, 80, 40));

        jLabel1011.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1011.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1011.setText("6.457");
        jLabel1011.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1011, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1690, 120, 40));

        jLabel1016.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1016.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1016.setText("<html> <body> <sup>221</sup> Fr </body> </html>");
        jLabel1016.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1016, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1690, 70, 40));

        jLabel1012.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1012.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1012.setText("α");
        jLabel1012.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1012, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1690, 80, 40));

        jLabel1042.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1042.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1042.setText("<html> <body> <sup>223</sup> Ra </body> </html>");
        jLabel1042.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1042, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1770, 80, 40));

        jLabel1043.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1043.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1043.setText("1.149");
        jLabel1043.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1043, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1770, 120, 40));

        jScrollPane8.setViewportView(jPanel22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Periodic_TableNew Tab = new Periodic_TableNew();
        Tab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton8KeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE)   {
      Periodic_TableNew Tab = new Periodic_TableNew();
       Tab.setVisible(true);
        this.setVisible(false); }
    }//GEN-LAST:event_jButton8KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Francium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Francium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Francium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Francium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Francium().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1007;
    private javax.swing.JLabel jLabel1008;
    private javax.swing.JLabel jLabel1010;
    private javax.swing.JLabel jLabel1011;
    private javax.swing.JLabel jLabel1012;
    private javax.swing.JLabel jLabel1014;
    private javax.swing.JLabel jLabel1015;
    private javax.swing.JLabel jLabel1016;
    private javax.swing.JLabel jLabel1019;
    private javax.swing.JLabel jLabel1020;
    private javax.swing.JLabel jLabel1026;
    private javax.swing.JLabel jLabel1035;
    private javax.swing.JLabel jLabel1038;
    private javax.swing.JLabel jLabel1039;
    private javax.swing.JLabel jLabel1040;
    private javax.swing.JLabel jLabel1042;
    private javax.swing.JLabel jLabel1043;
    private javax.swing.JLabel jLabel869;
    private javax.swing.JLabel jLabel870;
    private javax.swing.JLabel jLabel871;
    private javax.swing.JLabel jLabel873;
    private javax.swing.JLabel jLabel874;
    private javax.swing.JLabel jLabel875;
    private javax.swing.JLabel jLabel876;
    private javax.swing.JLabel jLabel893;
    private javax.swing.JLabel jLabel895;
    private javax.swing.JLabel jLabel896;
    private javax.swing.JLabel jLabel897;
    private javax.swing.JLabel jLabel898;
    private javax.swing.JLabel jLabel901;
    private javax.swing.JLabel jLabel902;
    private javax.swing.JLabel jLabel903;
    private javax.swing.JLabel jLabel904;
    private javax.swing.JLabel jLabel907;
    private javax.swing.JLabel jLabel908;
    private javax.swing.JLabel jLabel909;
    private javax.swing.JLabel jLabel910;
    private javax.swing.JLabel jLabel911;
    private javax.swing.JLabel jLabel912;
    private javax.swing.JLabel jLabel915;
    private javax.swing.JLabel jLabel917;
    private javax.swing.JLabel jLabel918;
    private javax.swing.JLabel jLabel919;
    private javax.swing.JLabel jLabel920;
    private javax.swing.JLabel jLabel921;
    private javax.swing.JLabel jLabel922;
    private javax.swing.JLabel jLabel923;
    private javax.swing.JLabel jLabel924;
    private javax.swing.JLabel jLabel925;
    private javax.swing.JLabel jLabel926;
    private javax.swing.JLabel jLabel927;
    private javax.swing.JLabel jLabel928;
    private javax.swing.JLabel jLabel929;
    private javax.swing.JLabel jLabel930;
    private javax.swing.JLabel jLabel931;
    private javax.swing.JLabel jLabel932;
    private javax.swing.JLabel jLabel936;
    private javax.swing.JLabel jLabel937;
    private javax.swing.JLabel jLabel938;
    private javax.swing.JLabel jLabel939;
    private javax.swing.JLabel jLabel940;
    private javax.swing.JLabel jLabel941;
    private javax.swing.JLabel jLabel942;
    private javax.swing.JLabel jLabel947;
    private javax.swing.JLabel jLabel948;
    private javax.swing.JLabel jLabel949;
    private javax.swing.JLabel jLabel952;
    private javax.swing.JLabel jLabel954;
    private javax.swing.JLabel jLabel955;
    private javax.swing.JLabel jLabel957;
    private javax.swing.JLabel jLabel958;
    private javax.swing.JLabel jLabel959;
    private javax.swing.JLabel jLabel960;
    private javax.swing.JLabel jLabel962;
    private javax.swing.JLabel jLabel963;
    private javax.swing.JLabel jLabel964;
    private javax.swing.JLabel jLabel965;
    private javax.swing.JLabel jLabel967;
    private javax.swing.JLabel jLabel979;
    private javax.swing.JLabel jLabel980;
    private javax.swing.JLabel jLabel981;
    private javax.swing.JLabel jLabel982;
    private javax.swing.JLabel jLabel983;
    private javax.swing.JLabel jLabel984;
    private javax.swing.JLabel jLabel985;
    private javax.swing.JLabel jLabel986;
    private javax.swing.JLabel jLabel987;
    private javax.swing.JLabel jLabel988;
    private javax.swing.JLabel jLabel989;
    private javax.swing.JLabel jLabel990;
    private javax.swing.JLabel jLabel991;
    private javax.swing.JLabel jLabel992;
    private javax.swing.JLabel jLabel993;
    private javax.swing.JLabel jLabel996;
    private javax.swing.JLabel jLabel998;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
