/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PeriodicTable;

import java.awt.event.KeyEvent;

/**
 *
 * @author MKS
 */
public class Iron extends javax.swing.JFrame {

    /**
     * Creates new form Iron
     */
    public Iron() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel869 = new javax.swing.JLabel();
        jLabel871 = new javax.swing.JLabel();
        jLabel872 = new javax.swing.JLabel();
        jLabel873 = new javax.swing.JLabel();
        jLabel874 = new javax.swing.JLabel();
        jLabel893 = new javax.swing.JLabel();
        jLabel895 = new javax.swing.JLabel();
        jLabel896 = new javax.swing.JLabel();
        jLabel897 = new javax.swing.JLabel();
        jLabel898 = new javax.swing.JLabel();
        jLabel899 = new javax.swing.JLabel();
        jLabel900 = new javax.swing.JLabel();
        jLabel901 = new javax.swing.JLabel();
        jLabel902 = new javax.swing.JLabel();
        jLabel903 = new javax.swing.JLabel();
        jLabel904 = new javax.swing.JLabel();
        jLabel907 = new javax.swing.JLabel();
        jLabel908 = new javax.swing.JLabel();
        jLabel909 = new javax.swing.JLabel();
        jLabel910 = new javax.swing.JLabel();
        jLabel912 = new javax.swing.JLabel();
        jLabel913 = new javax.swing.JLabel();
        jLabel914 = new javax.swing.JLabel();
        jLabel915 = new javax.swing.JLabel();
        jLabel917 = new javax.swing.JLabel();
        jLabel918 = new javax.swing.JLabel();
        jLabel919 = new javax.swing.JLabel();
        jLabel920 = new javax.swing.JLabel();
        jLabel921 = new javax.swing.JLabel();
        jLabel922 = new javax.swing.JLabel();
        jLabel923 = new javax.swing.JLabel();
        jLabel924 = new javax.swing.JLabel();
        jLabel925 = new javax.swing.JLabel();
        jLabel926 = new javax.swing.JLabel();
        jLabel927 = new javax.swing.JLabel();
        jLabel929 = new javax.swing.JLabel();
        jLabel930 = new javax.swing.JLabel();
        jLabel931 = new javax.swing.JLabel();
        jLabel932 = new javax.swing.JLabel();
        jLabel933 = new javax.swing.JLabel();
        jLabel934 = new javax.swing.JLabel();
        jLabel935 = new javax.swing.JLabel();
        jLabel938 = new javax.swing.JLabel();
        jLabel948 = new javax.swing.JLabel();
        jLabel949 = new javax.swing.JLabel();
        jLabel960 = new javax.swing.JLabel();
        jLabel961 = new javax.swing.JLabel();
        jLabel962 = new javax.swing.JLabel();
        jLabel963 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel876 = new javax.swing.JLabel();
        jLabel980 = new javax.swing.JLabel();
        jLabel981 = new javax.swing.JLabel();
        jLabel982 = new javax.swing.JLabel();
        jLabel983 = new javax.swing.JLabel();
        jLabel984 = new javax.swing.JLabel();
        jLabel985 = new javax.swing.JLabel();
        jLabel986 = new javax.swing.JLabel();
        jLabel987 = new javax.swing.JLabel();
        jLabel988 = new javax.swing.JLabel();
        jLabel989 = new javax.swing.JLabel();
        jLabel990 = new javax.swing.JLabel();
        jLabel991 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel936 = new javax.swing.JLabel();
        jLabel875 = new javax.swing.JLabel();
        jLabel870 = new javax.swing.JLabel();
        jLabel911 = new javax.swing.JLabel();
        jLabel975 = new javax.swing.JLabel();
        jLabel974 = new javax.swing.JLabel();
        jLabel968 = new javax.swing.JLabel();
        jLabel969 = new javax.swing.JLabel();
        jLabel967 = new javax.swing.JLabel();
        jLabel966 = new javax.swing.JLabel();
        jLabel943 = new javax.swing.JLabel();
        jLabel944 = new javax.swing.JLabel();
        jLabel964 = new javax.swing.JLabel();
        jLabel965 = new javax.swing.JLabel();
        jLabel941 = new javax.swing.JLabel();
        jLabel942 = new javax.swing.JLabel();
        jLabel939 = new javax.swing.JLabel();
        jLabel940 = new javax.swing.JLabel();
        jLabel947 = new javax.swing.JLabel();
        jLabel992 = new javax.swing.JLabel();
        jLabel993 = new javax.swing.JLabel();
        jLabel976 = new javax.swing.JLabel();
        jLabel1016 = new javax.swing.JLabel();
        jLabel1017 = new javax.swing.JLabel();
        jLabel1018 = new javax.swing.JLabel();
        jLabel1058 = new javax.swing.JLabel();
        jLabel1059 = new javax.swing.JLabel();
        jLabel1060 = new javax.swing.JLabel();
        jLabel1040 = new javax.swing.JLabel();
        jLabel1050 = new javax.swing.JLabel();
        jLabel1051 = new javax.swing.JLabel();
        jLabel1053 = new javax.swing.JLabel();
        jLabel1055 = new javax.swing.JLabel();
        jLabel1021 = new javax.swing.JLabel();
        jLabel1022 = new javax.swing.JLabel();
        jLabel1042 = new javax.swing.JLabel();
        jLabel1047 = new javax.swing.JLabel();
        jLabel978 = new javax.swing.JLabel();
        jLabel958 = new javax.swing.JLabel();
        jLabel994 = new javax.swing.JLabel();
        jLabel997 = new javax.swing.JLabel();
        jLabel999 = new javax.swing.JLabel();
        jLabel995 = new javax.swing.JLabel();
        jLabel1066 = new javax.swing.JLabel();
        jLabel1067 = new javax.swing.JLabel();
        jLabel1068 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel945 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel946 = new javax.swing.JLabel();
        jLabel970 = new javax.swing.JLabel();
        jLabel971 = new javax.swing.JLabel();
        jLabel1019 = new javax.swing.JLabel();
        jLabel1020 = new javax.swing.JLabel();
        jLabel1023 = new javax.swing.JLabel();
        jLabel1024 = new javax.swing.JLabel();
        jLabel1070 = new javax.swing.JLabel();
        jLabel1071 = new javax.swing.JLabel();
        jLabel1072 = new javax.swing.JLabel();
        jLabel1073 = new javax.swing.JLabel();
        jLabel1074 = new javax.swing.JLabel();
        jLabel1075 = new javax.swing.JLabel();
        jLabel1043 = new javax.swing.JLabel();
        jLabel1048 = new javax.swing.JLabel();
        jLabel1062 = new javax.swing.JLabel();
        jLabel1063 = new javax.swing.JLabel();
        jLabel1044 = new javax.swing.JLabel();
        jLabel1052 = new javax.swing.JLabel();
        jLabel1076 = new javax.swing.JLabel();
        jLabel1077 = new javax.swing.JLabel();
        jLabel1078 = new javax.swing.JLabel();
        jLabel1041 = new javax.swing.JLabel();
        jLabel1069 = new javax.swing.JLabel();
        jLabel1079 = new javax.swing.JLabel();
        jLabel1080 = new javax.swing.JLabel();
        jLabel1081 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iron");
        setPreferredSize(new java.awt.Dimension(585, 720));
        setResizable(false);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane8.setPreferredSize(new java.awt.Dimension(585, 720));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel869.setBackground(new java.awt.Color(255, 255, 255));
        jLabel869.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel869.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel869.setText("<html> <body> <center> <sub> 26 </sub> Fe</center> </body> </html>");
        jLabel869.setOpaque(true);
        jPanel23.add(jLabel869, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 550, 40));

        jLabel871.setBackground(new java.awt.Color(255, 153, 153));
        jLabel871.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel871.setForeground(new java.awt.Color(51, 51, 51));
        jLabel871.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel871.setText("<html> <body> <center> Iron</center> </body> </html>");
        jLabel871.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel871.setOpaque(true);
        jPanel23.add(jLabel871, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 40));

        jLabel872.setBackground(new java.awt.Color(229, 227, 228));
        jLabel872.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel872.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/800px-Iron_electrolytic_and_1cm3_cube.jpg"))); // NOI18N
        jLabel872.setOpaque(true);
        jPanel23.add(jLabel872, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 550, 240));

        jLabel873.setBackground(new java.awt.Color(255, 255, 255));
        jLabel873.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel873.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel873.setText("Lustrous metallic with a grayish tinge");
        jLabel873.setToolTipText("");
        jLabel873.setOpaque(true);
        jPanel23.add(jLabel873, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 550, 30));

        jLabel874.setBackground(new java.awt.Color(255, 153, 153));
        jLabel874.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel874.setForeground(new java.awt.Color(51, 51, 51));
        jLabel874.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel874.setText("<html> <body> <center> General properties  </center> </body> </html>");
        jLabel874.setOpaque(true);
        jPanel23.add(jLabel874, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 550, 40));

        jLabel893.setBackground(new java.awt.Color(255, 153, 153));
        jLabel893.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel893.setForeground(new java.awt.Color(51, 51, 51));
        jLabel893.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel893.setText("<html> <body> <center> Physical Properties </center> </body> </html>");
        jLabel893.setOpaque(true);
        jPanel23.add(jLabel893, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 550, 40));

        jLabel895.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel895.setText(" \tSolid");
        jLabel895.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel895, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 920, 320, 40));

        jLabel896.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel896.setText("Phase");
        jLabel896.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel896, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 920, 230, 40));

        jLabel897.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel897.setText("Density (near r.t.)");
        jLabel897.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel897, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 960, 230, 40));

        jLabel898.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel898.setText("<html>\n<body>\n7.874 g·cm\n<sup>−3</sup>\n</body>\n<html>");
        jLabel898.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel898, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 960, 320, 40));

        jLabel899.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel899.setText("Liquid density at m.p.");
        jLabel899.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel899, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1000, 230, 40));

        jLabel900.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel900.setText("<html> <body>6.98 g·cm <sup>−3</sup> </body> </html>");
        jLabel900.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel900, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1000, 320, 40));

        jLabel901.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel901.setText("Melting point");
        jLabel901.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel901, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1040, 230, 40));

        jLabel902.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel902.setText("1811 K, 1538 °C, 2800 °F");
        jLabel902.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel902, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1040, 320, 40));

        jLabel903.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel903.setText("Boiling point");
        jLabel903.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel903, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1080, 230, 40));

        jLabel904.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel904.setText("3134 K, 2862 °C, 5182 °F");
        jLabel904.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel904, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1080, 320, 40));

        jLabel907.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel907.setText("Heat of fusion");
        jLabel907.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel907, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1120, 230, 40));

        jLabel908.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel908.setText("<html> <body>  \t13.81   kJ·mol <sup>−1</sup> </body> </html>");
        jLabel908.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel908, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1120, 320, 40));

        jLabel909.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel909.setText("Heat of vaporization");
        jLabel909.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel909, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1160, 230, 40));

        jLabel910.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel910.setText("<html> <body>340  kJ·mol <sup>−1</sup> </body> </html>");
        jLabel910.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel910, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1160, 320, 40));

        jLabel912.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel912.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel912.setText("at T (K)");
        jLabel912.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel912, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1320, 120, 40));

        jLabel913.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel913.setText("<html>\n<body>\n25.10  J·mol\n<sup>−1</sup>\n·K<sup>−1</sup>\n</body>\n</html>\n");
        jLabel913.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel913, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1200, 320, 40));

        jLabel914.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel914.setText("Molar heat capacity");
        jLabel914.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel914, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1200, 230, 40));

        jLabel915.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel915.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel915.setText("1728");
        jLabel915.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel915, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1320, 60, 40));

        jLabel917.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel917.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel917.setText("1890");
        jLabel917.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel917, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1320, 60, 40));

        jLabel918.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel918.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel918.setText("1");
        jLabel918.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel918, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1280, 60, 40));

        jLabel919.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel919.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel919.setText("3132");
        jLabel919.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel919, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1320, 100, 40));

        jLabel920.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel920.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel920.setText("10");
        jLabel920.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel920, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 1280, 60, 40));

        jLabel921.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel921.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel921.setText("100 k");
        jLabel921.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel921, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1280, 100, 40));

        jLabel922.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel922.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel922.setText("100");
        jLabel922.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel922, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1280, 60, 40));

        jLabel923.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel923.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel923.setText("2091");
        jLabel923.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel923, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1320, 60, 40));

        jLabel924.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel924.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel924.setText("1 k");
        jLabel924.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel924, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1280, 70, 40));

        jLabel925.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel925.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel925.setText(" \t2346");
        jLabel925.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel925, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1320, 70, 40));

        jLabel926.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel926.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel926.setText("10 k");
        jLabel926.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel926, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1280, 80, 40));

        jLabel927.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel927.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel927.setText("2679");
        jLabel927.setToolTipText("");
        jLabel927.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel927, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1320, 80, 40));

        jLabel929.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel929.setText("Oxidation states");
        jLabel929.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel929, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1400, 230, 40));

        jLabel930.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel930.setText("Electronegativity");
        jLabel930.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel930, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1440, 230, 40));

        jLabel931.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel931.setText("6, 5, 4, 3, 2, 1, -1, -2 (amphoteric oxide)");
        jLabel931.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel931, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1400, 320, 40));

        jLabel932.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel932.setText("Ionization energies (more)");
        jLabel932.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel932, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1480, 230, 120));

        jLabel933.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel933.setText("<html> <body> 3rd:  2957   kJ·mol <sup>−1</sup> </body> </html>");
        jLabel933.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel933, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1560, 320, 40));

        jLabel934.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel934.setText("Atomic radius");
        jLabel934.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel934, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1600, 230, 40));

        jLabel935.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel935.setText("126 pm");
        jLabel935.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel935, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1600, 320, 40));

        jLabel938.setBackground(new java.awt.Color(255, 153, 153));
        jLabel938.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel938.setForeground(new java.awt.Color(51, 51, 51));
        jLabel938.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel938.setText("<html> <body> <center> Atomic properties </center> </body> </html>");
        jLabel938.setOpaque(true);
        jPanel23.add(jLabel938, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1360, 550, 40));

        jLabel948.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel948.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel948.setText("Vapor pressure");
        jLabel948.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel948, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1240, 550, 40));

        jLabel949.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel949.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel949.setText("P (Pa)");
        jLabel949.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel949, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1280, 120, 40));

        jLabel960.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel960.setText("<html> <body> 1st: 762.5 kJ·mol <sup>−1</sup> </body> </html> ");
        jLabel960.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel960, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1480, 320, 40));

        jLabel961.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel961.setText("<html> <body> 2nd: 1561.9   kJ·mol <sup>−1</sup> </body> </html>");
        jLabel961.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel961, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1520, 320, 40));

        jLabel962.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel962.setText("Covalent radius");
        jLabel962.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel962, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1640, 230, 40));

        jLabel963.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel963.setText("132±3 (low spin), 152±6 (high spin) pm");
        jLabel963.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel963, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1640, 320, 40));

        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jButton8.setText("Return To Table");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton8KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 378, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel876.setBackground(new java.awt.Color(255, 153, 153));
        jLabel876.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel876.setForeground(new java.awt.Color(51, 51, 51));
        jLabel876.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel876.setText("<html>\n<body>\n<center>\n\nAppearance\n\n</center>\n</body>\n</html>");
        jLabel876.setOpaque(true);
        jPanel23.add(jLabel876, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 550, 40));

        jLabel980.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel980.setText("Element category");
        jLabel980.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel980, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 230, 40));

        jLabel981.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel981.setText("Transition metal");
        jLabel981.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel981, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 320, 40));

        jLabel982.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel982.setText("Pronunciation");
        jLabel982.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel982, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 230, 40));

        jLabel983.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel983.setText(" \t/ˈaɪ.ərn/");
        jLabel983.setToolTipText("");
        jLabel983.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel983, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 320, 40));

        jLabel984.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel984.setText("Group, period, block");
        jLabel984.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel984, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 230, 40));

        jLabel985.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel985.setText("8, 4, d");
        jLabel985.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel985, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 320, 40));

        jLabel986.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel986.setText("Name, symbol, number");
        jLabel986.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel986, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 40));

        jLabel987.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel987.setText("Iron, Fe, 26");
        jLabel987.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel987, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 320, 40));

        jLabel988.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel988.setText("Standard atomic weight");
        jLabel988.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel988, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 230, 40));

        jLabel989.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel989.setText("55.845(2)");
        jLabel989.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel989, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 320, 40));

        jLabel990.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel990.setText("Electron configuration");
        jLabel990.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel990, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 230, 190));

        jLabel991.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel991.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel991.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/558px-Electron_shell_026_Iron.svg.png"))); // NOI18N
        jLabel991.setText("26:Iron    2, 8,14, 2");
        jLabel991.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel991.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel991.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel23.add(jLabel991, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 690, 320, 190));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("<html>\n<body>\n[Ar]3d<sup>6</sup>4s<sup>2</sup>\n<br>2, 8, 14, 2 \n\n</body>\n</html>\n\n\n\n\n");
        jPanel23.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, 130, 50));

        jLabel936.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel936.setText(" \t1.83 (Pauling scale)");
        jLabel936.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jLabel936, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1440, 320, 40));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel875.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel875.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel875.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/558px-Electron_shell_003_Lithium.svg.png"))); // NOI18N
        jLabel875.setText("3:Lithium                   2,1");
        jLabel875.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel875.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel22.add(jLabel875, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 790, 320, 150));

        jLabel870.setBackground(new java.awt.Color(255, 153, 153));
        jLabel870.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel870.setForeground(new java.awt.Color(51, 51, 51));
        jLabel870.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel870.setText("<html> <body> <center> Most stable isotopes </center> </body> </html>");
        jLabel870.setOpaque(true);
        jPanel22.add(jLabel870, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2560, 550, 40));

        jLabel911.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel911.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel911.setText("Main article: Isotopes of iron");
        jLabel911.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel911, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2600, 550, 40));

        jLabel975.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel975.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel975.setText("170 GPa");
        jLabel975.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel975, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2320, 320, 40));

        jLabel974.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel974.setText("Bulk modulus");
        jLabel974.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel974, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2320, 230, 40));

        jLabel968.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel968.setText("211 GPa");
        jLabel968.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel968, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2240, 320, 40));

        jLabel969.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel969.setText("Young's modulus");
        jLabel969.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel969, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2240, 230, 40));

        jLabel967.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel967.setText("<html>\n<body>\n(25 °C) 11.8 µm·m\n<sup>−1</sup>·K<sup>−1</sup>\n</body>\n</html>");
        jLabel967.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel967, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2160, 320, 40));

        jLabel966.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel966.setText("Thermal expansion");
        jLabel966.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel966, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2160, 230, 40));

        jLabel943.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel943.setText("Thermal conductivity");
        jLabel943.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel943, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2120, 230, 40));

        jLabel944.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel944.setText("<html> <body> 80.4  W·m <sup>−1</sup>·K<sup>−1</sup> </body> </html>");
        jLabel944.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel944, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2120, 320, 40));

        jLabel964.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel964.setText("(20 °C) 96.1 nΩ·m");
        jLabel964.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel964, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2080, 320, 40));

        jLabel965.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel965.setText("Electrical resistivity");
        jLabel965.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel965, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2080, 230, 40));

        jLabel941.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel941.setText("Magnetic ordering");
        jLabel941.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel941, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2000, 230, 80));

        jLabel942.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel942.setText("1043 K");
        jLabel942.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel942, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2040, 320, 40));

        jLabel939.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel939.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel939.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/109px-Cubic-face-centered.svg.png"))); // NOI18N
        jLabel939.setText("Face-centered cubic        ");
        jLabel939.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel939.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel22.add(jLabel939, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1860, 320, 140));

        jLabel940.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel940.setText("Crystal structure");
        jLabel940.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel940, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1720, 230, 280));

        jLabel947.setBackground(new java.awt.Color(255, 153, 153));
        jLabel947.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel947.setForeground(new java.awt.Color(51, 51, 51));
        jLabel947.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel947.setText("<html> <body> <center> Miscellanea</center> </body> </html>");
        jLabel947.setOpaque(true);
        jPanel22.add(jLabel947, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1680, 550, 40));

        jLabel992.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel992.setText("CAS registry number");
        jLabel992.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel992, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2520, 230, 40));

        jLabel993.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel993.setText("7439-89-6");
        jLabel993.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel993, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2520, 320, 40));

        jLabel976.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel976.setText("Speed of sound (thin rod)");
        jLabel976.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel976, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2200, 230, 40));

        jLabel1016.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1016.setText("<html>\n<body>\n(r.t.) (electrolytic)\n5120  m·s\n<sup>−1</sup>\n</body>\n</html> \t");
        jLabel1016.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1016, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2200, 320, 40));

        jLabel1017.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1017.setText(" \t0.29");
        jLabel1017.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1017, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2360, 320, 40));

        jLabel1018.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1018.setText("Poisson ratio");
        jLabel1018.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1018, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2360, 230, 40));

        jLabel1058.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1058.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1058.setText("5.8%");
        jLabel1058.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1058, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2680, 110, 40));

        jLabel1059.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1059.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1059.setText("<html> <body> <sup>54</sup>Fe</body> </html>");
        jLabel1059.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1059, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2680, 70, 40));

        jLabel1060.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1060.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1060.setText("<html> <body> <sup>56</sup>Fe</body> </html>");
        jLabel1060.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1060, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2760, 70, 40));

        jLabel1040.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1040.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1040.setText("<html>\n<body>\nβ<sup>−</sup>\n</body>\n</html>");
        jLabel1040.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1040, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 2920, 80, 40));

        jLabel1050.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1050.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1050.setText(" ?");
        jLabel1050.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1050, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2680, 120, 40));

        jLabel1051.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1051.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1051.setText("<html> <body> <sup>54</sup>Cr</body> </html>");
        jLabel1051.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1051, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 2680, 80, 40));

        jLabel1053.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1053.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1053.setText("3.978 \t");
        jLabel1053.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1053, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2920, 120, 40));

        jLabel1055.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1055.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1055.setText("<html>\n<body>\n>3.1 ×10<sup>22</sup> y\n</body>\n</html>");
        jLabel1055.setToolTipText("");
        jLabel1055.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1055, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2680, 90, 40));

        jLabel1021.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1021.setText("Brinell hardness");
        jLabel1021.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1021, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2480, 230, 40));

        jLabel1022.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1022.setText("490 MPa");
        jLabel1022.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1022, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2480, 320, 40));

        jLabel1042.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1042.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1042.setText(" \t91.72%");
        jLabel1042.setToolTipText("");
        jLabel1042.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1042, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2760, 110, 40));

        jLabel1047.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1047.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1047.setText("<html>\n<body>\n<sup>56</sup>Fe is stable with 30 neutrons\n</body>\n</html>");
        jLabel1047.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1047, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2760, 370, 40));

        jLabel978.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel978.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel978.setText("iso");
        jLabel978.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel978, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2640, 70, 40));

        jLabel958.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel958.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel958.setText("NA");
        jLabel958.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel958, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2640, 110, 40));

        jLabel994.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel994.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel994.setText("half-life");
        jLabel994.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel994, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2640, 90, 40));

        jLabel997.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel997.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel997.setText("DM \t");
        jLabel997.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel997, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 2640, 80, 40));

        jLabel999.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel999.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel999.setText("DE (MeV)");
        jLabel999.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel999, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2640, 120, 40));

        jLabel995.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel995.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel995.setText("DP");
        jLabel995.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel995, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 2640, 80, 40));

        jLabel1066.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1066.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1066.setText("2ε capture");
        jLabel1066.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1066, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 2680, 80, 40));

        jLabel1067.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1067.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1067.setText("<html> <body> <sup>60</sup>Co</body> </html>");
        jLabel1067.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1067, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 2920, 80, 40));

        jLabel1068.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1068.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1068.setText("1.565");
        jLabel1068.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1068, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2880, 120, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("between 1185–1667 K");
        jPanel22.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1970, -1, -1));

        jLabel945.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel945.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel945.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PeriodicTable/Lithiumstr.png"))); // NOI18N
        jLabel945.setText("Body-centered cubic        ");
        jLabel945.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel945.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel22.add(jLabel945, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1720, 320, 140));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("a=286.65 pm;");
        jPanel22.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1840, -1, -1));

        jLabel946.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel946.setText("Ferromagnetic");
        jLabel946.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel946, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2000, 320, 40));

        jLabel970.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel970.setText("Shear modulus");
        jLabel970.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel970, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2280, 230, 40));

        jLabel971.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel971.setText("82 GPa");
        jLabel971.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel971, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2280, 320, 40));

        jLabel1019.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1019.setText("4");
        jLabel1019.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1019, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2400, 320, 40));

        jLabel1020.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1020.setText("Mohs hardness");
        jLabel1020.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1020, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2400, 230, 40));

        jLabel1023.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1023.setText("Vickers hardness");
        jLabel1023.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1023, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2440, 230, 40));

        jLabel1024.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1024.setText(" \t608 MPa");
        jLabel1024.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1024, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2440, 320, 40));

        jLabel1070.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1070.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1070.setText("<html> <body> <sup>55</sup>Fe</body> </html>");
        jLabel1070.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1070, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2720, 70, 40));

        jLabel1071.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1071.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1071.setText("syn");
        jLabel1071.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1071, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2720, 110, 40));

        jLabel1072.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1072.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1072.setText("2.73 y");
        jLabel1072.setToolTipText("");
        jLabel1072.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1072, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2720, 90, 40));

        jLabel1073.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1073.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1073.setText("ε capture");
        jLabel1073.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1073, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 2720, 80, 40));

        jLabel1074.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1074.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1074.setText("0.231");
        jLabel1074.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1074, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2720, 120, 40));

        jLabel1075.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1075.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1075.setText("<html> <body> <sup>55</sup>Mn</body> </html>");
        jLabel1075.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1075, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 2720, 80, 40));

        jLabel1043.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1043.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1043.setText("2.2%");
        jLabel1043.setToolTipText("");
        jLabel1043.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1043, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2800, 110, 40));

        jLabel1048.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1048.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1048.setText("<html>\n<body>\n<sup>57</sup>Fe is stable with 31 neutrons\n</body>\n</html>");
        jLabel1048.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1048, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2800, 370, 40));

        jLabel1062.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1062.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1062.setText("<html> <body> <sup>57</sup>Fe</body> </html>");
        jLabel1062.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1062, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2800, 70, 40));

        jLabel1063.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1063.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1063.setText("<html> <body> <sup>58</sup>Fe</body> </html>");
        jLabel1063.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1063, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2840, 70, 40));

        jLabel1044.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1044.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1044.setText("0.28%");
        jLabel1044.setToolTipText("");
        jLabel1044.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1044, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2840, 110, 40));

        jLabel1052.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1052.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1052.setText("<html>\n<body>\n<sup>58</sup>Fe is stable with 32 neutrons\n</body>\n</html>");
        jLabel1052.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1052, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2840, 370, 40));

        jLabel1076.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1076.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1076.setText("syn");
        jLabel1076.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1076, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2880, 110, 40));

        jLabel1077.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1077.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1077.setText("44.503 d");
        jLabel1077.setToolTipText("");
        jLabel1077.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1077, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2880, 90, 40));

        jLabel1078.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1078.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1078.setText("<html> <body> <sup>59</sup>Fe</body> </html>");
        jLabel1078.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1078, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2880, 70, 40));

        jLabel1041.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1041.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1041.setText("<html>\n<body>\nβ<sup>−</sup>\n</body>\n</html>");
        jLabel1041.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1041, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 2880, 80, 40));

        jLabel1069.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1069.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1069.setText("<html> <body> <sup>59</sup>Co</body> </html>");
        jLabel1069.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1069, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 2880, 80, 40));

        jLabel1079.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1079.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1079.setText("<html>\n<body>\n2.6×10\n<sup>6</sup> y\n</body>\n</html>");
        jLabel1079.setToolTipText("");
        jLabel1079.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1079, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 2920, 90, 40));

        jLabel1080.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1080.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1080.setText("syn");
        jLabel1080.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1080, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2920, 110, 40));

        jLabel1081.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1081.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1081.setText("<html> <body> <sup>60</sup>Fe</body> </html>");
        jLabel1081.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jLabel1081, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2920, 70, 40));

        jScrollPane8.setViewportView(jPanel22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Periodic_TableNew Tab = new Periodic_TableNew();
        Tab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton8KeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE)   {
      Periodic_TableNew Tab = new Periodic_TableNew();
       Tab.setVisible(true);
        this.setVisible(false); }
    }//GEN-LAST:event_jButton8KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Iron().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1016;
    private javax.swing.JLabel jLabel1017;
    private javax.swing.JLabel jLabel1018;
    private javax.swing.JLabel jLabel1019;
    private javax.swing.JLabel jLabel1020;
    private javax.swing.JLabel jLabel1021;
    private javax.swing.JLabel jLabel1022;
    private javax.swing.JLabel jLabel1023;
    private javax.swing.JLabel jLabel1024;
    private javax.swing.JLabel jLabel1040;
    private javax.swing.JLabel jLabel1041;
    private javax.swing.JLabel jLabel1042;
    private javax.swing.JLabel jLabel1043;
    private javax.swing.JLabel jLabel1044;
    private javax.swing.JLabel jLabel1047;
    private javax.swing.JLabel jLabel1048;
    private javax.swing.JLabel jLabel1050;
    private javax.swing.JLabel jLabel1051;
    private javax.swing.JLabel jLabel1052;
    private javax.swing.JLabel jLabel1053;
    private javax.swing.JLabel jLabel1055;
    private javax.swing.JLabel jLabel1058;
    private javax.swing.JLabel jLabel1059;
    private javax.swing.JLabel jLabel1060;
    private javax.swing.JLabel jLabel1062;
    private javax.swing.JLabel jLabel1063;
    private javax.swing.JLabel jLabel1066;
    private javax.swing.JLabel jLabel1067;
    private javax.swing.JLabel jLabel1068;
    private javax.swing.JLabel jLabel1069;
    private javax.swing.JLabel jLabel1070;
    private javax.swing.JLabel jLabel1071;
    private javax.swing.JLabel jLabel1072;
    private javax.swing.JLabel jLabel1073;
    private javax.swing.JLabel jLabel1074;
    private javax.swing.JLabel jLabel1075;
    private javax.swing.JLabel jLabel1076;
    private javax.swing.JLabel jLabel1077;
    private javax.swing.JLabel jLabel1078;
    private javax.swing.JLabel jLabel1079;
    private javax.swing.JLabel jLabel1080;
    private javax.swing.JLabel jLabel1081;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel869;
    private javax.swing.JLabel jLabel870;
    private javax.swing.JLabel jLabel871;
    private javax.swing.JLabel jLabel872;
    private javax.swing.JLabel jLabel873;
    private javax.swing.JLabel jLabel874;
    private javax.swing.JLabel jLabel875;
    private javax.swing.JLabel jLabel876;
    private javax.swing.JLabel jLabel893;
    private javax.swing.JLabel jLabel895;
    private javax.swing.JLabel jLabel896;
    private javax.swing.JLabel jLabel897;
    private javax.swing.JLabel jLabel898;
    private javax.swing.JLabel jLabel899;
    private javax.swing.JLabel jLabel900;
    private javax.swing.JLabel jLabel901;
    private javax.swing.JLabel jLabel902;
    private javax.swing.JLabel jLabel903;
    private javax.swing.JLabel jLabel904;
    private javax.swing.JLabel jLabel907;
    private javax.swing.JLabel jLabel908;
    private javax.swing.JLabel jLabel909;
    private javax.swing.JLabel jLabel910;
    private javax.swing.JLabel jLabel911;
    private javax.swing.JLabel jLabel912;
    private javax.swing.JLabel jLabel913;
    private javax.swing.JLabel jLabel914;
    private javax.swing.JLabel jLabel915;
    private javax.swing.JLabel jLabel917;
    private javax.swing.JLabel jLabel918;
    private javax.swing.JLabel jLabel919;
    private javax.swing.JLabel jLabel920;
    private javax.swing.JLabel jLabel921;
    private javax.swing.JLabel jLabel922;
    private javax.swing.JLabel jLabel923;
    private javax.swing.JLabel jLabel924;
    private javax.swing.JLabel jLabel925;
    private javax.swing.JLabel jLabel926;
    private javax.swing.JLabel jLabel927;
    private javax.swing.JLabel jLabel929;
    private javax.swing.JLabel jLabel930;
    private javax.swing.JLabel jLabel931;
    private javax.swing.JLabel jLabel932;
    private javax.swing.JLabel jLabel933;
    private javax.swing.JLabel jLabel934;
    private javax.swing.JLabel jLabel935;
    private javax.swing.JLabel jLabel936;
    private javax.swing.JLabel jLabel938;
    private javax.swing.JLabel jLabel939;
    private javax.swing.JLabel jLabel940;
    private javax.swing.JLabel jLabel941;
    private javax.swing.JLabel jLabel942;
    private javax.swing.JLabel jLabel943;
    private javax.swing.JLabel jLabel944;
    private javax.swing.JLabel jLabel945;
    private javax.swing.JLabel jLabel946;
    private javax.swing.JLabel jLabel947;
    private javax.swing.JLabel jLabel948;
    private javax.swing.JLabel jLabel949;
    private javax.swing.JLabel jLabel958;
    private javax.swing.JLabel jLabel960;
    private javax.swing.JLabel jLabel961;
    private javax.swing.JLabel jLabel962;
    private javax.swing.JLabel jLabel963;
    private javax.swing.JLabel jLabel964;
    private javax.swing.JLabel jLabel965;
    private javax.swing.JLabel jLabel966;
    private javax.swing.JLabel jLabel967;
    private javax.swing.JLabel jLabel968;
    private javax.swing.JLabel jLabel969;
    private javax.swing.JLabel jLabel970;
    private javax.swing.JLabel jLabel971;
    private javax.swing.JLabel jLabel974;
    private javax.swing.JLabel jLabel975;
    private javax.swing.JLabel jLabel976;
    private javax.swing.JLabel jLabel978;
    private javax.swing.JLabel jLabel980;
    private javax.swing.JLabel jLabel981;
    private javax.swing.JLabel jLabel982;
    private javax.swing.JLabel jLabel983;
    private javax.swing.JLabel jLabel984;
    private javax.swing.JLabel jLabel985;
    private javax.swing.JLabel jLabel986;
    private javax.swing.JLabel jLabel987;
    private javax.swing.JLabel jLabel988;
    private javax.swing.JLabel jLabel989;
    private javax.swing.JLabel jLabel990;
    private javax.swing.JLabel jLabel991;
    private javax.swing.JLabel jLabel992;
    private javax.swing.JLabel jLabel993;
    private javax.swing.JLabel jLabel994;
    private javax.swing.JLabel jLabel995;
    private javax.swing.JLabel jLabel997;
    private javax.swing.JLabel jLabel999;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
